services:
  weidy-api:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - indy-node
  indy-node:
    image: bcgov/indy-node
    container_name: indy-node
    ports:
      - "9701-9708:9701-9708"
    environment:
      - NODE_NAME=Node1